### ISSUE TITLE
Add ISO-639 for Fon language

### ISSUE THREAD

**Issue by chrisemezue** [huggingface/widgets-server#19]
Hello,
I am working on the WavVec sprint (https://github.com/huggingface/transformers/blob/master/examples/research_projects/wav2vec2/FINE_TUNE_XLSR_WAV2VEC2.md#how-to-upload-my-trained-checkpoint) and I am fine-tuning the wav2vec model on Fon (https://en.wikipedia.org/wiki/Fon_language)
However, I am supposed to use the ISO code on https://huggingface.co/languages and that of Fon is not there.

Please is it possible to add the iso details for Fon?

ISO-639: fon

**Comment by julien-c** [comment]
Yes, added it

Thanks!
