### ISSUE TITLE
default ASR or TTS tasks?

### ISSUE THREAD

**Issue by bayartsogt-ya** [huggingface/widgets-server#20]
Wondering if ASR or TTS task defaults can be configured by this repo?

**Comment by julien-c** [comment]
Yes, great idea.

TTS is easy as samples can just be an array of strings.

For ASR, the best format would be to link to an externally hosted audio URL, with associated text title, i.e something like:
```typescript
[ "automatic-speech-recognition", [
		{
			label: `Librispeech sample 1`,
			src: `https://cdn-media.huggingface.co/speech_samples/sample1.flac`,
		},
...
```

i.e. same format used in https://huggingface.co/facebook/wav2vec2-base-960h/blob/main/README.md

Do you want to open a PR for some of the languages?

**Comment by bayartsogt-ya** [comment]
@julien-c
Yeah, I'd love to start from "Mongolian".
1. Can I add [here](https://github.com/huggingface/widgets-server/blob/master/DefaultWidget.ts#L416)?
2. Should `src` should be on `cdn-media.huggingface.co` or any source?

**Comment by julien-c** [comment]
1. Yes
2. Any source should work, though we might need to whitelist the host on the Inference API’s side (cc @Narsil @n1t0)

**Comment by bayartsogt-ya** [comment]
@julien-c 
Thank you for confirmation! I'll create PR and let's change source then if it is in the blacklist.

**Comment by Narsil** [comment]
You can use any URL after we made a small modification to the hub to make the process safe for any URL.
Before that the URL needs to be on `cdn-media.huggingface.co` yes.

**Comment by bayartsogt-ya** [comment]
@Narsil 
Thank you for the explanation @Narsil

**Comment by Narsil** [comment]
Btw, just to be explicit, the URL will need to have enabled CORS policy (it's the case for imgur by default for instance) just to make sure that people on the hub can actually view and send the file to the API.
